create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.trips (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  destination text not null,
  start_date date not null,
  end_date date not null,
  days integer not null check (days > 0),
  budget numeric(10,2) not null check (budget > 0),
  currency text not null default 'USD',
  travel_style text not null,
  interest text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(id) on delete cascade,
  trip_id bigint references public.trips(id) on delete set null,
  rating_value integer not null check (rating_value between 1 and 5),
  review_text text,
  created_at timestamptz not null default now()
);

insert into public.users (name, email, password_hash, role)
values (
  'TripCraft Admin',
  'admin@tripcraft.com',
  '240be518fabd2724ddb6f04eeb1da5967448d7e831c08c8fa822809f74c720a9',
  'admin'
)
on conflict (email) do update
set
  name = excluded.name,
  password_hash = excluded.password_hash,
  role = excluded.role;
